### ISSUE TITLE
Missed strings for translations

### ISSUE THREAD

**Issue by ITotalJustice** [ITotalJustice/sphaira#21]
see #19

**Comment by Yorunokyujitsu** [comment]
<p float="left">
  <img src="https://i.imgur.com/au2ygia.jpg" width="400" />
  <img src="https://i.imgur.com/6a55kY3.jpg" width="400" />
  <img src="https://i.imgur.com/EJptyO3.jpg" width="400" />
  <img src="https://i.imgur.com/aWXu3ue.jpg" width="400" />
  <img src="https://i.imgur.com/e45FmOu.jpg" width="400" />
  <img src="https://i.imgur.com/rtFyEWc.jpg" width="400" />
</p>


I gathered and organized the missing strings in [lang.json](https://github.com/Yorunokyujitsu/sphaira/blob/test/assets/romfs/i18n/en.json) by section.
And translated Korean and Japanese, and it seems to be working.
https://github.com/Yorunokyujitsu/sphaira/blob/test/assets/romfs/i18n/ko.json
https://github.com/Yorunokyujitsu/sphaira/blob/test/assets/romfs/i18n/ja.json

The string in the Homebrew Delete message box is too long, so I changed it to show only the path.
https://github.com/Yorunokyujitsu/sphaira/blob/test/sphaira/source/ui/menus/homebrew.cpp#L102

https://github.com/Yorunokyujitsu/sphaira/commit/9f9936f9683e6b0b463673637b845ece632f5068

**Comment by ITotalJustice** [comment]
fixed in #32
