### ISSUE TITLE
the time is not sync with UTC time zone

### ISSUE THREAD

**Issue by WE1ZARD** [ITotalJustice/sphaira#23]
Is it possible to have a feature of NTP (Network Time Protocol) in following updates?
So that we can sync time and set time zone of sphaira.

As all online features will require time sync before using it.

**Comment by cucholix** [comment]
Was to open this same issue lol

**Comment by ITotalJustice** [comment]
Hi, just to clarify are you saying that the time shown in sphaira is different to the time displayed on the home menu?

**Comment by cucholix** [comment]
The time displayed in sphaira is different from time displayed in home menu

**Comment by shadow2560** [comment]
The overlay [QuickNTP](https://github.com/nedex/QuickNTP) is capable ot doing time sync for the console.

**Comment by ITotalJustice** [comment]
Fwiw I have already fixed this, I just haven't pushed the commit yet. The issue was I was using gmtime() which returns...gm time, who would've known 😄 I should be using localtime() which returns...local time
