### ISSUE TITLE
[Broken Feature] Forwarders don't work anymore

### ISSUE THREAD

**Issue by glitch128** [ITotalJustice/sphaira#24]
as of atmosphere 1.8.0, forwarders do not work. please remove the "Install Forwarder" feature to avoid people creating issues about forwarders not working. as well as an issue with that installing forwarders will get people banned if in sysMMC connected to nintendo, as I view this as a ban risk for people who don't know this

**Comment by ITotalJustice** [comment]
They work for me,, have you tried it?

**Comment by glitch128** [comment]
no, I was just told that they were updated to work with 1.8.0
I was also told that they require piracy patches to work though
it's still a ban risk though

**Comment by ITotalJustice** [comment]
Firstly, it's not a ban risk as the ncas cannot be installed without patches installed, which if they are, it's safe to assume they're already doing ban worthy stuff.

It also displays a huge warning about the ban risk before installing.

Finally, reporting something as broken without testing (or even using the app by the sounds of it) is not helpful

**Comment by glitch128** [comment]
I just tested it on emuMMC, and it does not require piracy patches specifically, but it works with the patches I got from https://dardel.codeberg.page/nxdumpguide/emummc_guide/

**Comment by ITotalJustice** [comment]
> I just tested it on emuMMC, and it does not require piracy patches specifically, but it works with the patches I got from https://dardel.codeberg.page/nxdumpguide/emummc_guide/

You do not require patches to dump a game card.

You do require patches to install / launch modified ncas. Those patches you linked are "piracy patches", I am not sure why you think otherwise. To Nintendo, modified ncas indicate piracy. It doesn't matter if it's your "legal backup", they will ban you regardless.
