### ISSUE TITLE
[UI Change] Install forwarder warning

### ISSUE THREAD

**Issue by glitch128** [ITotalJustice/sphaira#25]
I feel like that the "Install Forwarder" warning does not induce a sense of danger as it should. For impactfulness, I would change the warning to look more like the "delete save data" warning, as that induces that this is a dangerous action via visuals and the fact that you have to wait for the delete option to become available, giving you time to contemplate this decision.
example image:
![image](https://github.com/user-attachments/assets/7de12bdb-4791-437e-a390-f417bc1d8d4a)

**Comment by ITotalJustice** [comment]
Not doing this, its unessesary.

**Comment by ITotalJustice** [comment]
To expand on this a little, the user has to do the following things to install a forwarder:
- have piracy patches installed.
- click on a app and navigate all the way down to install forwarder option and click on said option.
- press right on the dpad to the Install button when the pop up is displayed, ignoring the big bold letters saying WARNING, that is also translated in multiple languages, and then click A to install.

If someone does all of that, then they want to install a forwarder. It cannot be done by accident. I am not not willing to make the UX worse for everyone else to cater to anyone silly enough to go through all the above steps and claim they didn't know what they were doing
