### ISSUE TITLE
Language auto doesn't seems to work

### ISSUE THREAD

**Issue by shadow2560** [ITotalJustice/sphaira#27]
At least with french "FR_fr" console, the auto language set the language of the app to English, not tested by set an other console's language . If I force the langauge to French it works.

**Comment by ninstar** [comment]
This affects other languages as well, I'm guessing it has something to do with sphaira expecting the locales to have the exact same region code as the one set in the console?

**Comment by shadow2560** [comment]
I don't realy know, I wanted to make some tests by adding some logs in source code but compiling, at least on Windows (environement up to date on Windows 11), seems to be a problem. The first time it compile properly but the second time it doesn't work, "multiple ptarget patterns" error", even if the first compilation doesn't go to the end (compile.make files are modified during build and the second time it doesn't work) so I must delete the "build" folder and re-launch the compilation from the begining, this is too long so I have given up.

**Comment by ITotalJustice** [comment]
Been really busy with work so I won't be able to look at this until a few days.

The call to get the language is here https://github.com/ITotalJustice/sphaira/blob/3178f115964fc2b5d5426e6215c3db5d3f434432/sphaira/source/i18n.cpp#L47 which should be correct.

I do notice that I don't init set service here https://github.com/ITotalJustice/sphaira/blob/3178f115964fc2b5d5426e6215c3db5d3f434432/sphaira/source/main.cpp#L50 however I thought set was initialised by libnx automatically, maybe I was wrong.

**Comment by ITotalJustice** [comment]
> I don't realy know, I wanted to make some tests by adding some logs in source code but compiling, at least on Windows (environement up to date on Windows 11), seems to be a problem. The first time it compile properly but the second time it doesn't work, "multiple ptarget patterns" error", even if the first compilation doesn't go to the end (compile.make files are modified during build and the second time it doesn't work) so I must delete the "build" folder and re-launch the compilation from the begining, this is too long so I have given up.

Can you post the errors when building? Did you build using cmake preset? It should be "cmake --preset Release" to configure and then "cmake --build --preset Release" to build.

**Comment by shadow2560** [comment]
I used these commands except that I use "MinSizeRel" preset, here is the result of the "cmake --build --preset MinSizeRel" command the second time:
```
cmake : hbl/CMakeFiles/hbl.dir/compiler_depend.make:4: *** multiple target patterns.  Stop.
make[1]: *** [CMakeFiles/Makefile2:217: hbl/CMakeFiles/hbl.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
_deps/yyjson-build/CMakeFiles/yyjson.dir/compiler_depend.make:4: *** multiple target patterns.  Stop.
make[1]: *** [CMakeFiles/Makefile2:767: _deps/yyjson-build/CMakeFiles/yyjson.dir/all] Error 2
sphaira/CMakeFiles/libpulsar.dir/compiler_depend.make:4: *** multiple target patterns.  Stop.
make[1]: *** [CMakeFiles/Makefile2:344: sphaira/CMakeFiles/libpulsar.dir/all] Error 2
_deps/minini-sphaira-build/CMakeFiles/minIni-sphaira.dir/compiler_depend.make:4: *** multiple target patterns.  Stop.
make[1]: *** [CMakeFiles/Makefile2:736: _deps/minini-sphaira-build/CMakeFiles/minIni-sphaira.dir/all] Error 2
_deps/nanovg-build/CMakeFiles/nanovg.dir/compiler_depend.make:4: *** multiple target patterns.  Stop.
make[1]: *** [CMakeFiles/Makefile2:612: _deps/nanovg-build/CMakeFiles/nanovg.dir/all] Error 2
[  1%] Built target hbl_npdm
[  2%] Built target fill_vsh
make: *** [Makefile:136: all] Error 2
```

**Comment by shadow2560** [comment]
I've tried to compile on a ubuntu wsl console and like that it seems to work, it's at least a possibility for me to do my own tests quicker than on my pur Windows environment.

**Comment by shadow2560** [comment]
OK I've found the problem, you seem to not use "setInitialize();" so the condition in "/sphaira/source/i18n.cpp" file "if (R_SUCCEEDED(setGetSystemLanguage(&languageCode))) {" is never true, just as I suspected it.

If you want I can do a pull request but do you prefer I initialize "set" directly in the "i18n.cpp" file (directly in the case for index == 0 and closing the service at the end of the case juste before the break line) or when initializing the app and exiting the service when denitializing the app?

**Comment by shadow2560** [comment]
Finaly I have made a pull request #31 to fix the problem, I fixed it by init and exit the Set service in the main.cpp file. For the cmake compile error on Windows maybe I will open an other issue, for now I close this one cause it is fixed.
