### ISSUE TITLE
Out the bound text

### ISSUE THREAD

**Issue by cucholix** [ITotalJustice/sphaira#28]
Some messages don’t fit into the rectangular text box, and get outside it
![F79AED03-7343-4675-B668-ADB9810E49EA](https://github.com/user-attachments/assets/d8424534-0507-4bfd-9e88-815dae09753b)

**Comment by ITotalJustice** [comment]
![2024122115010800-CA43EC7375AB1E2BC8AFC050C0941918](https://github.com/user-attachments/assets/e0198e03-6cd2-45e8-a4b6-7edc861eaca9)
![2024122115010300-CA43EC7375AB1E2BC8AFC050C0941918](https://github.com/user-attachments/assets/f7ecadb6-7f6a-42c1-bb56-d1c7675d1025)
ive changed it so the text wraps round. is the padding okay between the lines? the default padding looks like:
![2024122114572000-CA43EC7375AB1E2BC8AFC050C0941918](https://github.com/user-attachments/assets/4a039d37-c0fc-45b0-bbe4-3d5f802eec69)
which looks a bit crammed to me
