### ISSUE TITLE
FileBrowser->App wrong button label

### ISSUE THREAD

**Issue by cucholix** [ITotalJustice/sphaira#30]
While FileBrowser is open the R button is labeled as “App” but pressing it will launch to Homebrew menu, same thing happens when you are in App menu, the L button is labeled as “Fs” but pressing it will launch Homebrew menu.
![3BCBFC4F-AD0E-457F-BB3D-DDBD8E31C076](https://github.com/user-attachments/assets/e2ec94d1-ebf3-4568-9a74-16237bea8b3f)

Also it could be possible label “Fs” as “SD”, after all we are browsing the SD, and have no idea what Fs stands for 😅

**Comment by ITotalJustice** [comment]
"Fs" is short for FileSystem. I did consider "Fb" for FileBrowser, but i personally prefer Fs 😄 

I have done the following changes:
- App has been renamed to Store
- App is now used to mean the homebrew menu, as its a collection of apps.
- Whilst in FileBrowser, "R" will show "App"
- Whilst in Appstore, "L" will show "App"
- Whilst in Homebrew, "L" will show "Fs", "R will show "Store

Any other naming suggestions are welcome!

I won't rename Fs to SD however, i may later on extend Fs to support more than just the sd card, like i did with ftpsrv.
