### ISSUE TITLE
HBMenu replacement option not enabled if done manualy

### ISSUE THREAD

**Issue by shadow2560** [ITotalJustice/sphaira#34]
If the "hbmenu.nro" file is replaced by Sphaira manualy without setting up the option in Sphaira (no config file or option not set in it) the corresponding option is set to disabled. I don't know if it's intentional or not, the label of the option let me think that it is but for me the option is a little strange and could be improved to be more understandable without breaking the actual app functions.

Maybe it could be a good idea to set the option with the nro path launched (with the function "App::IsHbmenu()") instead having a config option in the config file and a default value? If yes the option label could be changed by something like "HBMenu replacement" or "App replace HBMenu". And with the associed variable the app could know what to do, if not launched as HBMenu and option is enabled it backup the actual HBMenu and replace it and if it's launched as HBMenu and the option is disabled the app try to restore the backup (if it doesn't exist it stop the process to not brake the homebrew launch or maybe it could try to download the last version of HBMenu from Github to replace it or the last version of HBMenu could be integrated in the romfs of the homebrew but this option could be anoying because when a new version of the HBMenu is available the app must be recompiled to integrate it) and copy the app into "/switch/sphaira" folder.

**Comment by ITotalJustice** [comment]
I agree the option could be improved, but I feel like it would just need a popup box explaining each option. Ie , on enabling, show a popup saying something like "hbmenu will be replaced by sphaira on exit. Hbmenu will be backed up to /switch/hbmenu.nro". And when enabled -> disabled, show popup asking if the user wants to restore hbmenu.

As for your suggestions
- I would not add an option to replace hbmenu with any app. This will break people's setup and lock them out of launching homebrew if they don't know they're doing. Ie, replacing hbmenu with daybreak
- if the user manually copies sphaira as hbmenu, sphaira has no way of knowing if the user had just disabled the "replace" config option or manually moved the file. As such, removing sphaira and replacing it with hbmenu probably isn't a good idea.
- if we do my suggestion, when trying to restore hbmenu, if it's not found, display a popup explaining to the user that they can download hbmenu from the app store.

**Comment by shadow2560** [comment]
No I'm not suggesting to replace HBMenu with any app, By using your condition like "if (R_SUCCEEDED(nro_get_nacp("/hbmenu.nro", nacp)) && std::strcmp(nacp.lang[0].name, "sphaira")) {" we can check easily what is copied or not like you've already done.

Maybe I will try to create a branch to propose my modification, I think my idea is not too hard to make, I just need to know how popup works in your app. Your code is difficult for me to understand and to master, especialy the GUI part cause I'm realy not familiar with GUI coding but with a little time I think I could at least do this properly and show precisely what I have in mind.
