### ISSUE TITLE
Please add 'B' key to exit Sphaira

### ISSUE THREAD

**Issue by Sean-China** [ITotalJustice/sphaira#39]
Could you please add 'B' key to exit Sphaira in the new version? Currently, after entering Sphaira from the Forwarder, the only way to close it is to return to the homepage

**Comment by ITotalJustice** [comment]
Press plus to exit

**Comment by Sean-China** [comment]
Can we add press 'B' to exit in addition to the plus? Most applications support the B button for exiting, including the older version of hbmenu. This way, using sphaira to replace hbmenu won't affect user habits.

**Comment by ITotalJustice** [comment]
> Can we add press 'B' to exit in addition to the plus? Most applications support the B button for exiting, including the older version of hbmenu. This way, using sphaira to replace hbmenu won't affect user habits.

No sorry.
