### ISSUE TITLE
Chinese Translation.

### ISSUE THREAD

**Issue by do-kiss** [ITotalJustice/sphaira#4]
Here is my attempt at translating it into Chinese as accurately as possible. It should already be about 95% complete. The original machine translation was very difficult to understand.I will provide a more refined translation later by incorporating the context of usage scenarios.

**Comment by do-kiss** [comment]
[zh.json.txt](https://github.com/user-attachments/files/18165412/zh.json.txt)

**Comment by ITotalJustice** [comment]
Sorry only just seen this. I just merged a pr here https://github.com/WE1ZARD/sphaira/blob/684c46226a7e40457982c599b141f564ec004b67/assets/romfs/i18n/zh.json is there any further changes you'd make?

**Comment by do-kiss** [comment]
> Sorry only just seen this. I just merged a pr here https://github.com/WE1ZARD/sphaira/blob/684c46226a7e40457982c599b141f564ec004b67/assets/romfs/i18n/zh.json is there any further changes you'd make?

This is the most refined Chinese translation that best fits real-world application scenarios. I compiled and performed as many page tests as possible with it, and it should be the best version so far.
[zh.json](https://github.com/user-attachments/files/18166126/zh.json)

**Comment by do-kiss** [comment]
Additionally, I have a suggestion: could Sphaire support loading languages from external files, similar to Ultrahand’s multilingual approach where translation JSON files are externalized? This would make it more flexible.

**Comment by ITotalJustice** [comment]
> Additionally, I have a suggestion: could Sphaire support loading languages from external files, similar to Ultrahand’s multilingual approach where translation JSON files are externalized? This would make it more flexible.

Yes I considerd this, however I decided against it because it may result in translations being made and not shared. Where's with the current system, it encourages users to open and issue / pull request.

That being said, having to push a new release for each language change seems like a bit of a pain. Maybe adding external translations is the best approach, and add an updater for translations that would pull from this repo. I'll think on it

**Comment by ITotalJustice** [comment]
in commit https://github.com/ITotalJustice/sphaira/commit/9966e57e1222727520dc48290d49ed034d5bc1f8 i added support for loading translations locally in `/config/sphaira/i18n/zh.json` (replace zh with the language name). 
this will take priority of the built in translations.
if the file is not found locally, it will use the built in translations. the idea is that it will help aid those creating translations :)

closing as pr was sent in https://github.com/ITotalJustice/sphaira/pull/12 and https://github.com/ITotalJustice/sphaira/pull/3
