### ISSUE TITLE
MTP and touch control

### ISSUE THREAD

**Issue by mhh996378373** [ITotalJustice/sphaira#40]
When will the previous MTP function be added back?
Also, are you considering adding touch control?

**Comment by ITotalJustice** [comment]
Mtp was removed as it was kinda redundant as atmosphere comes bundled with a mtp server.

As for touch, see #15

**Comment by mhh996378373** [comment]
> Mtp was removed as it was kinda redundant as atmosphere comes bundled with a mtp server.
> 
> As for touch, see #15

The MTP function is not redundant. To use the MTP function of Atmosphere, you need to enter Sphaira and click the USB File Transfer tool. Previously, you only needed to enter Sphaira.

**Comment by ITotalJustice** [comment]
> > Mtp was removed as it was kinda redundant as atmosphere comes bundled with a mtp server.
> > As for touch, see #15
> 
> The MTP function is not redundant. To use the MTP function of Atmosphere, you need to enter Sphaira and click the USB File Transfer tool. Previously, you only needed to enter Sphaira.

I have now added back the mtp server in the latest release 😃

**Comment by mhh996378373** [comment]
> > > Mtp 被删除了，因为它有点多余，因为 Atmospheric 捆绑了 mtp 服务器。
> > > 至于 touch，请参阅#15
> > 
> > 
> > MTP 功能并非多余。要使用 Atmosphere 的 MTP 功能，您需要进入 Sphaira 并单击 USB 文件传输工具。以前，您只需要进入 Sphaira。
> 
> 我现在已在最新版本中添加回 mtp 服务器 😃

good！
