### ISSUE TITLE
Question for EXFAT formated SD

### ISSUE THREAD

**Issue by shadow2560** [ITotalJustice/sphaira#47]
Did Sphaira has any specific protection for manipulations on files with EXFAT SD (crc verification when copying for example) or like others homebrews it could cause datas corruptions except if transfert is brutaly interrupted? Personaly I don't use EXFAT and I always tell to the users to not use it but Sphaira has a file explorer and it could be goog to know if it could cause corruptions when helping people.

**Comment by ITotalJustice** [comment]
Yes, by blocking exit with appletLockExit, it ensures that everything is closed properly before exiting. Although if anyone is using exfat, they will experience corruption, regardless if they use sphaira or not, so I don't care to support it.
