### ISSUE TITLE
L-R button icons swap

### ISSUE THREAD

**Issue by cucholix** [ITotalJustice/sphaira#5]
For consistency sake L shoulder button icon should be placed at left of the R shoulder button.
Currently L shoulder icon is at the right of R shoulder.
![0B771854-698A-412F-BA86-CD1D953427EC](https://github.com/user-attachments/assets/b5aceaae-dedd-4a05-b17c-1158e2a16c18)

**Comment by ITotalJustice** [comment]
Ah yeah I didn't even notice lol. I'll give later today

**Comment by ITotalJustice** [comment]
fixed in https://github.com/ITotalJustice/sphaira/commit/9966e57e1222727520dc48290d49ed034d5bc1f8
