### ISSUE TITLE
features suggestion : Use ftpsrv settings

### ISSUE THREAD

**Issue by HoRy205** [ITotalJustice/sphaira#59]
I use ftpsrv a lot, so it would be more convenient if you could add an option to use the same config for sphaira.

**Comment by ITotalJustice** [comment]
What config options do you need?

**Comment by HoRy205** [comment]
It would be useful if user,pass,log,  enables showing all available mount points at root could be read from config/ftpsrv/config.ini!

**Comment by ITotalJustice** [comment]
fixed in https://github.com/ITotalJustice/sphaira/commit/cb7fb0e50695b74b883903c6d52da750d554b910
